version: "3.9"
services:
  frontend:
    build:
      context: ./front-side
      dockerfile: Dockerfile
    container_name: edu-front
    ports:
      - "3000:3000"

    # attention le chargement du front est très lent
    # soyez patients pour l'installation des dépendances

  database:
    image: postgres
    container_name: edu-data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_pass
      - POSTGRES_DB=edu-database
    volumes:
      - /edu-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back-api
      dockerfile: Dockerfile
    container_name: edu-back
    ports:
     - "9898:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/edu-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret_pass
      - SPRING_DATASOURCE_DRIVER-CLASS= org.postgresql.Driver

# Créer les images Docker
#docker-compose build

# Démarrer les conteneurs
#docker-compose up -d

# Arrêter les conteneurs
#docker-compose down -v

# Supprimer les conteneurs
#docker-compose rm

# Supprimer les images Docker
#docker-compose rmi
